name: Cypress Tests

on:
  workflow_dispatch:      # Pour lancer manuellement
  schedule:
    - cron: "0 * * * *"   # üïê Toutes les heures (√† XX:00)
  push:
    branches:
      - main              # Facultatif : lance √† chaque push

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress on Cloud
        uses: cypress-io/github-action@v6
        with:
          record: true     # Envoi des r√©sultats vers Cypress Cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
